const TIPO_VALOR={
    DECIMAL: 'VAL_DECIMAL',
    CADENA: 'VAL_CADENA',
    ENTERO: 'VAL_ENTERO',
    BOOL: 'VAL_BOLEANO',
    CHAR: 'VAL_CHAR',
    UNARIA:'VAL_UNARIA', 
    IDENTIFICADOR: 'VAL_IDENTIFICADOR',
    VECTOR: 'VAL_VECTOR',
    LISTA: 'VAL_LISTA',
}
module.exports=TIPO_VALOR;