const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    DEC_METODO:'DEC_METODO',
    MAIN: 'MAIN',
    IF: 'IF',   
    IFE: 'IFE',
    ELSEIF: 'ELSEIF',
    IFEIF: 'IFEIF',
    SWITCH: 'SWITCH',
    CASE: 'CASE',    
    WHILE: 'WHILE',
    BREAK: 'BREAK',
    CONTINUE: 'CONTINUE',
    RETURN: 'RETURN',
}
module.exports = TIPO_INSTRUCCION;