const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    DEC_METODO:'DEC_METODO',
    MAIN: 'MAIN',
    IF: 'IF',   
}
module.exports = TIPO_INSTRUCCION;